library/src/fragment/fragment-ifc-importer/geometry.ts
Will also need to be fixed in bim-fragment for fragment loading. I will submit a PR there as well.
=> Fix bug with doubleSided materials

package.json, src/core/ButtonComponent/index.ts, src/core/ToolbarComponent/index.ts, src/core/UIManager/index.html, src/core/UIManager/index.ts, src/core/index.ts, src/types/base-types.ts, src/types/component.ts, src/types/components.ts
This is the first edition of a set of components to easily add viewer interaction through UI. The components added were:
- UIManager: Responsable of adding the UI components to the viewer container and make them nice and neat.
- Button: Component to create buttons and add interaction to them. Mainly used to provide other components with a default button to execute its functionalities.
- Toolbar: Container of button components. This can be added either top, right, bottom or left in the viewer container.
=> First edition of UI Components

resources/styles.css, src/core/PropertiesProcessor/index.html, src/core/PropertiesProcessor/index.ts, src/core/ScreenCuller/index.ts, src/core/ToolsComponent/index.ts, src/core/index.ts, src/fragments/FragmentHighlighter/index.ts, src/fragments/FragmentIfcLoader/index.ts, src/fragments/FragmentTree/index.html, src/fragments/FragmentTree/index.ts, src/fragments/FragmentTree/tree-item.ts, src/fragments/index.ts, src/ui/ButtonComponent/index.ts, src/ui/SimpleUIComponent/index.ts, src/ui/ToolbarComponent/index.ts, src/ui/UIManager/top.css, src/ui/index.ts
**PropertiesProcessor**
- Component that allows you to take IFC properties from `FragmentGroup` and structure them to be able to be shown in a table. In the short term, is very likely to not take the properties from `FragmentGroup` but from an external JSON file. Nonetheless, it should work the same.
- Added a simple example of how the component works.
**SimpleUIComponent**
- Base UI Component for other UI components to extend from. Not used yet in current UI Components.
**FragmentHighligther**
- Added `highlightEvents` that triggers when elements are highlighted or the highlighter was cleared out.
- Now extends from Component.
- Selection is now a public property.
- Changed parenting of the highlighter mesh.
**ToolsComponent**
- Added `onToolAdded` and `onToolRemoved` events. …
=> Added PropertiesProcessor component

src/core/PropertiesProcessor/index.ts, src/fragments/FragmentGroups/index.ts, src/fragments/FragmentManager/index.ts
Little PropertiesProcessor fix
=> Little PropertiesProcessor fix

src/core/SimpleClipper/index.html
=> Simple Clipper Tutorial Initial draft

src/core/SimpleDimensions/index.html
Tutorial for OBC.SimpleDimensions
=> Simple Dimensions Tutorial

src/core/ScreenCuller/index.html, src/navigation/ShadowDropper/index.html
1. Tutorial for Shadow Dropper
2. Screen Culler Initial Draft
=> Shadow Dropper Tutorial

src/core/ScreenCuller/index.html
Screen Culler Final Fix for Tutorial
=> Screen Culler Final Draft

src/navigation/OrthoPerspectiveCamera/index.html, src/navigation/PostproductionRenderer/index.html
Tutorial for Post Production
- Outline and Ambient Occlusion
Tutorial for OrthoPerspective Camera
- Basic Cube added 
- dat.GUI controls to set navigation mode added.
=> Post Production Tutorial & OrthoPerspective Camera Tutorial

src/navigation/CubeMap/index.ts
Added the ability to change the CubeMap position and size. Also, fixed orientation issue when using the compiled version.
---
=> feat(components): updated CubeMap component

.github/workflows/publish-npm.yml, .github/workflows/release-please.yml
~**NOTE:** Please do **not** push this yet! It is still undergoing testing processes to ensure its correct functionality.~
**UPDATE:** It has been proven to work [here](https://github.com/oxcabe/ifcjs-components/actions/runs/5170934442/jobs/9314172481). Furthermore, it indicates that [this line](https://github.com/IFCjs/components/blob/6163b9c0213dd85393ceb6161982c27a6bb18186/package.json#L7) has to be removed for the npmjs release workflow to succeed, which could be included in this PR before merging.
This PR addresses and fixes what was wrong with https://github.com/IFCjs/components/pull/48. In order to improve the chances of this ops integration working, a tool called [actionlint](https://github.com/rhysd/actionlint) was used to validate the correct structure of the workflow.
---
=> fix(project-config): fix npm-release.yml workflow

README.md
This PR fixes the tests badge, which was associated to the former `yaml` extension. Now it correctly points to [![Tests](https://github.com/IFCjs/components/actions/workflows/tests.yml/badge.svg)](https://github.com/IFCjs/components/actions/workflows/tests.yml).
---
=> chore(badges): fix tests workflow badge

README.md
=> chore(main): Update README.md

src/fragments/FragmentExploder/index.html
Tutorial for Fragment Exploder
---
=> Fragment Exploder tutorial

src/core/MaterialManager/index.html
- Example that demonstrated usage of `Material Manager` Component
- Tutorial for using `Material Manager` Component
---
=> Material Manager Example + Tutorial

src/fragments/FragmentPlans/index.html
- Tutorial for using `PlanNavigator`
=> Fragment plans tutorial

src/ifc/IfcPropertiesUtils/index.ts
Extend IfcPropertiesUtils to support finding item by guid
=> Extend IfcPropertiesUtils to support finding item by guid

src/navigation/MiniMap/index.html
=> MiniMap Tutorial

src/fragments/FragmentBoundingBox/index.html
Tutorial for Fragment Bounding Box
=> Fragment Bounding Box Tutorial

src/core/ScreenCuller/index.ts
Changes the behaviour inside ScreenCuller when reading render target pixels. Uses WebGLSync and promises to wait for the GPU to be idle before attempting to read the pixels. This results in no main thread blocking as was the case in the previous implementation.
=> Async readPixels replacement in ScreenCuller

src/fragments/FragmentTree/index.html
=> Fragment Tree Tutorial

package.json, resources/rollup.config.mjs, tsconfig.json
This PR expands the project configuration to support generating [typedoc](https://typedoc.org/) based documentation, which is required for completing the `packages` strategy refactor taking place in [IFCjs/docs](https://github.com/IFCjs/docs).
I have checked that the package builds correctly. It should also be checked that the package works as expected when imported after these changes.
=> feat(docs): implement typedoc config

package-lock.json, package.json, src/civil/RoadNavigator/index.ts, src/core/Components/index.ts, src/core/ScreenCuller/index.ts, src/core/Simple2DScene/index.ts, src/core/SimpleGrid/index.ts, src/core/SimpleScene/index.ts, src/core/ToolsComponent/index.ts, src/fragments/FragmentBoundingBox/index.ts, src/fragments/FragmentCacher/index.ts, src/fragments/FragmentClassifier/index.ts, src/fragments/FragmentClipStyler/index.ts, src/fragments/FragmentExploder/index.ts, src/fragments/FragmentHider/index.ts, src/fragments/FragmentHighlighter/index.ts, src/fragments/FragmentIfcLoader/index.ts, src/fragments/FragmentIfcLoader/src/data-converter.ts, src/fragments/FragmentPlans/index.ts, src/fragments/FragmentTree/index.ts, src/ifc/IfcPropertiesFinder/index.ts, src/import-export/dxf-exporter/index.ts, src/import-export/dxf-exporter/src/edge-projector.ts, src/navigation/EdgesClipper/index.ts, src/navigation/EdgesClipper/src/clipping-edges.ts, src/navigation/ShadowDropper/index.ts, src/navigation/ViewpointsManager/index.ts, yarn.lock
This PR adds the features described in issue https://github.com/IFCjs/components/issues/183.
---
=> feat(components): Tools component improvements

src/base-types/base-types.ts, src/base-types/component.ts, src/core/SimpleScene/index.ts, src/fragments/FragmentClipStyler/index.ts, src/fragments/FragmentHighlighter/index.ts
Implements a configurable interface as proposed in issue https://github.com/IFCjs/components/issues/174. Also, the existing tools that were using a setup method like the SimpleScene and FragmentHighlighter were updated accordingly to implement the interface.
---
=> feat(components): 174 - Define a Configurable interface for tools to implement.

src/core/SimpleRaycaster/index.ts
Updated the raycaster to be more maintainable. Reduced repeated code.
This could potentially be ignored :)
---
=> updated raycaster to be more maintainable

src/fragments/FragmentHighlighter/index.ts, src/fragments/FragmentTree/index.html, src/fragments/FragmentTree/index.ts, src/fragments/FragmentTree/src/tree-item.ts, src/ui/CheckboxInput/index.ts, src/ui/FloatingWindow/index.ts, src/ui/TreeView/index.ts
Allows to use the FragmentTree to hide/show elements. Solves #195. 
https://github.com/IFCjs/components/assets/56475338/84b8c3f5-6135-4294-84a8-523d2dce31b3
---
=> feat: implement visibility checkboxes in fragmenttree

src/fragments/FragmentIfcLoader/index.ts, src/fragments/FragmentIfcLoader/src/data-converter.ts, src/ifc/IfcPropertiesManager/index.html, src/ifc/IfcPropertiesManager/index.ts, src/ifc/IfcPropertiesManager/src/prop-actions.ts, src/ifc/IfcPropertiesManager/src/pset-actions.ts
This PR solves https://github.com/IFCjs/components/issues/101#issuecomment-1837642643.
---
=> fix(components): Wrong expressIDs on export

src/core/Components/index.ts, src/ui/UIManager/index.ts
This PR implements feature https://github.com/IFCjs/components/issues/189.
---
=> feat(components): 189 - Auto CSS Styles

src/fragments/FragmentCacher/index.ts
This PR solves issue https://github.com/IFCjs/components/issues/224.
---
=> fix(components): 224 - QuerySelector failing on SimpleUICard

src/fragments/FragmentIfcLoader/src/data-converter.ts
This solves issue https://github.com/IFCjs/components/issues/207.
---
=> fix(components): Fixed malformed headers(#270)

package.json, resources/styles.css, src/ui/UIManager/index.ts, tailwind.config.js
This solves issue https://github.com/IFCjs/components/issues/113.
---
=> fix(components): Scoped CSS to the viewer container

src/navigation/OrthoPerspectiveCamera/src/first-person-mode.ts, src/navigation/OrthoPerspectiveCamera/src/orbit-mode.ts
This PR solved issue https://github.com/IFCjs/components/issues/184.
---
=> fix(components): 184 - Fixed navigation break on first person mode

src/ui/SimpleUIComponent/index.ts
This PR solves issue https://github.com/IFCjs/components/issues/237.
---
=> fix(components): Slot's parent missing in UIComponents

src/core/LocalCacher/index.ts, src/core/ScreenCuller/index.ts, src/fragments/FragmentCacher/index.ts, src/fragments/FragmentManager/index.ts
This solves issue https://github.com/IFCjs/components/issues/212.
---
=> fix: ScreenCuller buggy when multiple models loaded

src/measurement/LengthMeasurement/index.ts
I opened this [issue](https://github.com/IFCjs/components/issues/194) which was partially fixed in [pr](https://github.com/IFCjs/components/pull/199) by @HoyosJuan . It seems that the modification should be applied in setupEvents function in LengthMeasurement component.
---
=> fix(components): 194 - complete fix of LengthMeasurement bug while UI Disabled.

package.json, resources/styles.css, src/core/LocalCacher/index.ts, src/core/ScreenCuller/index.html, src/core/ScreenCuller/index.ts, src/fragments/FragmentBoundingBox/index.ts, src/fragments/FragmentCacher/index.ts, src/fragments/FragmentHighlighter/index.ts, src/fragments/FragmentIfcLoader/src/data-converter.ts, src/fragments/FragmentManager/index.ts, src/measurement/LengthMeasurement/index.ts, src/navigation/OrthoPerspectiveCamera/src/first-person-mode.ts, src/navigation/OrthoPerspectiveCamera/src/orbit-mode.ts, src/ui/SimpleUIComponent/index.ts, src/ui/UIManager/index.ts, tailwind.config.js
This PR implements feature https://github.com/IFCjs/components/issues/190.
---
=> feat(components): Coordinate FragmentsModel when loaded with FragmentsManager

src/annotation/ArrowAnnotation/index.ts, src/annotation/CircleAnnotation/index.ts, src/annotation/DrawManager/index.html, src/annotation/DrawManager/index.ts, src/annotation/RectangleAnnotation/index.ts, src/annotation/TextAnnotation/index.ts, src/base-types/base-svg-annotation.ts, src/core/SimpleSVGViewport/index.ts
This solves issue https://github.com/IFCjs/components/issues/253.
---
=> fix(components): Updated annotation components

package.json, yarn.lock
This addresses issue https://github.com/IFCjs/components/issues/263.
---
=> feat: Moved mapbox to peer dependencies

src/fragments/FragmentClassifier/index.ts
This PR solves issue https://github.com/IFCjs/components/issues/260.
---
=> fix: FragmentsClassifier.byPredefineType now creates a set of strings

src/core/Components/index.ts
This PR solves issue https://github.com/IFCjs/components/issues/257.
---
=> fix: components.dispose failed when ui disabled

src/measurement/LengthMeasurement/index.ts, src/measurement/LengthMeasurement/src/index.ts
This PR solves issue https://github.com/IFCjs/components/issues/147.
---
=> fix: length measurement visualization problem

src/core/Components/index.ts
This PR takes care of complementing commit https://github.com/IFCjs/components/commit/83fc9eccc60ce439d3b6a04f1ee12c13c993021a by attending https://github.com/IFCjs/components/pull/267#pullrequestreview-1826622395.
---
=> fix: used internal variables on component dispose

src/fragments/FragmentIfcLoader/index.ts
=> feat: Set log level of FragmentIfcLoader

src/ifc/IfcPropertiesManager/index.html, src/ui/SimpleUIComponent/index.ts
Updates the properties manager example
---
=> feat: updated properties manager example

src/fragments/FragmentIfcLoader/index.ts
=> FragmentIfcLoader add custom locate file handler function to webIfc init call

src/ifc/IfcPropertiesUtils/index.ts
=> fix(IfcPropertiesUtils): Use safe navigation operator in getEntityName

src/civil/RoadPlanNavigator/src/plan-highlighter.ts
Added markings at end and starting points to dimension lines for all type of objects.
=> Added markings to dimension lines for all objects

src/civil/RoadPlanNavigator/index.ts, src/civil/RoadPlanNavigator/src/plan-highlighter.ts
Lines and geometries of dimension lines finished for any type of object clicked in RoadPlanNavigator (Circular Arcs, Lines or Clothoids). Methods were added to update the scale and the offset automatically when changing the zoom or the Floating Window size. Dispose method added for all objects created.
=> Correction: Markup tool lines geometry and logic 

packages/components/src/civil/Civil3DNavigator/example.ts, packages/components/src/civil/CivilCrossSectionNavigator/example.ts, packages/components/src/civil/CivilElevationNavigator/example.ts, packages/components/src/civil/CivilElevationNavigator/index.ts, packages/components/src/civil/CivilPlanNavigator/example.ts, packages/components/src/civil/CivilPlanNavigator/src/plan-highlighter.ts, packages/components/src/core/Simple2DMarker/src/marker-manager.ts, packages/components/src/fragments/FragmentIfcLoader/example.ts
Added fontSize and offset as inputs for addCivilVerticalMarker and added a updateOffset method to adapt those two values in real time when adjusting window size and zoom level in the Elevation Navigator window. 
Checked routes to access example civil model. Fixed small issue with the example of FragmentIfcLoader. 
---
=> Elevation labels fix

packages/components/package.json, packages/components/vite.config.ts
This PR updates the Vite configuration to include both .mjs and .cjs files in the core library build.
---
=> Library builld updates for .mjs and .cjs

packages/components/src/civil/Civil3DNavigator/index.ts, packages/components/src/civil/CivilElevationNavigator/index.ts, packages/components/src/civil/CivilNavigator/index.ts, packages/components/src/civil/CivilNavigator/src/curve-highlighter.ts, packages/components/src/civil/CivilNavigator/src/kp-manager.ts, packages/components/src/civil/CivilPlanNavigator/index.ts, packages/components/src/civil/CivilPlanNavigator/src/plan-highlighter.ts
New civil tools feature. Added KP Label to the marker, showing current KP when hovering and selecting and alignment in Plan and Elevation View windows.
=> New kp labels

packages/core/src/ifc/Utils/properties-utils.ts
Obvious error in units factors
=> fix(properties-utils): fix decimiter units

packages/front/src/measurement/LengthMeasurement/index.ts
Added the feature to cancel Lengthmeasurement like its possible in Areameasurement!
=> feat(front): Add keydown event for Lengthmeasurement

packages/core/src/ifc/IfcIsolator/example.html, packages/core/src/ifc/IfcIsolator/example.ts, packages/core/src/ifc/IfcIsolator/index.ts, packages/core/src/ifc/index.ts
Added IfcIsolator class
fixes #514
Implement the feature to isolate IFC elements with the given IDs and export them into a new IFC file.
---
=> feat: add a Tool for isolating graphical elements and export to valid IFC

packages/front/src/fragments/IfcStreamer/src/geometry-culler-renderer.ts
Added `RawShaderMaterial` to objects with transparency below `0.9` to allow the culler to detect objects behind glass-like surfaces, improving visibility in the scene.
Review focus: Ensure compatibility with existing culler logic and confirm no performance issues.
---
=> Improve Culler Visibility Through Transparent Objects
