- library/src/fragment/fragment-ifc-importer/data-converter.ts
Fixes [This issue](https://github.com/IFCjs/components/issues/6). It might be a bit hacky, but it means that it doesn't break on models with no storeys.
> In models with no storeys, handle all fragments as instanced items

- library/src/components.ts
- library/src/core/simple-renderer.ts
- library/src/fragment/fragment-grouper.ts
- library/src/fragment/fragment-ifc-importer/data-converter.ts
- library/src/fragment/fragment.ts
1. Awaited on `saveModelData()` under `generateFragmentData()` to have properties available when loading IFC models.
2. Added a handy `setVisibility` function on FragmentGrouper.
3. Changed `requestAnimationFrame` to `setAnimationLoop` to [add support for WebXR].(https://threejs.org/docs/index.html#api/en/renderers/WebGLRenderer.setAnimationLoop).
4. Added alpha to simple-renderer.
> Improvements over DataConverter, FragmentsGrouper and Components.

- .github/workflows/publish-npm.yml
- .github/workflows/release-please.yml
This PR addresses the case where the `publish-npm` workflow doesn't execute after the `release-please` workflow publishes a new release.
It seems that the following snippet
```
on:
release:
types: [published]
```
doesn't handle releases published by other workflows, as explained [here](https://docs.github.com/en/actions/using-workflows/triggering-a-workflow#triggering-a-workflow-from-a-workflow). This commit corrects this behavior and ensures the workflow runs by directly calling it from the release steps.
The caller workflow also checks that a release has been correctly created before proceeding. In case a manual release is created and published, the `publish-npm` workflow will also perform a release, which could be useful for hot-fixes and patches.
> chore(releases): run publish-npm on any published releases

- .github/ISSUE_TEMPLATE/bug_report.yml
- .github/ISSUE_TEMPLATE/feature_request.yml
This PR removes the "label" field from the issue templates config.
> fix(project-config): remove labels field from issue templates

- .github/workflows/release-please.yml
This PR fixes the use of the npm-release.yml workflow when running the release-please.yml workflow, as explained [here](https://docs.github.com/en/actions/using-workflows/reusing-workflows).
---
> fix(project-config): fix npm-release.yml use in release-please.yml

- .github/workflows/publish-npm.yml
This PR fixes the `publish-npm` workflow by using the `publish-repo` script listed in the `package.json` file.
This commit is analogous to https://github.com/IFCjs/fragment/commit/faca55bcf7b0ae4da85664edcc8b681a1bd71f69.
---
> fix(publish-repo): fix publish repo with yarn command

- src/core/SimpleRaycaster/index.ts
The variable for a get from a raycaster was named scene. This should be raycaster.
nothing was changed except name.
---
> refactor(raycaster): correct variable naming in SimpleRaycaster constructor

- .github/workflows/publish-npm.yml
This PR fixes the following error on the publish-npm GitHub Actions workflow:
```
.github/workflows/publish-npm.yml:12:9: unexpected key "type" for "secrets" section. expected one of "description", "required" [syntax-check]
|
12 |         type: string
|         ^~~~~
```
---
> fix(workflow): remove "type" key from publish-npm.yml

- src/navigation/OrthoPerspectiveCamera/index.ts
This PR solves the issue https://github.com/IFCjs/components/issues/172. The reason why it was failing, is because the camera is set before the viewer is initialized, but the UI components need the viewer to be initialized in order for them to be setup. A simple callback when the viewer is initialized did the trick.
---
> fix(components): Fixed OrthoPerspectiveCamera UI bug in OBC 1.1.7

- src/navigation/OrthoPerspectiveCamera/index.ts
- src/navigation/OrthoPerspectiveCamera/src/projections.ts
When:
1. Switch to Ortho projection from Perspective
2. Zoom in/out
3. Change back to Perspective
A visual disparity camera disparity is seen, due to the different zoom levels.
This fix translates the ortho zoom back to perspective distance instead of using the saved value.
Note: I think this should be the default behaviour, but don't want to break any code, especially around plans, so it's implemented with a flag 
---
> fix: ortho/perspective zoom disparity

- src/fragments/FragmentClassifier/index.ts
- src/fragments/FragmentHighlighter/index.ts
- src/fragments/FragmentManager/index.ts
- src/ifc/IfcPropertiesFinder/index.ts
- src/ifc/IfcPropertiesProcessor/index.ts
- src/ui/SimpleUIComponent/index.ts
This PR solves issue https://github.com/IFCjs/components/issues/170. Basically, it removes the model specific data after a FragmentsGroup has been disposed.
---
> fix(components): 170 - Deleted unused data after fragments disposed.

- src/core/SimpleClipper/index.ts
- src/navigation/EdgesClipper/src/edges-plane.ts
This PR solves issue https://github.com/IFCjs/components/issues/130. Basically, both enabled and visible in the clippers must match... they weren't.
---
> fix(components): 130 - SimpleClipper/EdgesClipper visibility bug

- src/ifc/IfcPropertiesProcessor/index.ts
- src/navigation/OrthoPerspectiveCamera/index.ts
- src/utils/VertexPicker/index.ts
This PR solves issue https://github.com/IFCjs/components/issues/194. The problem was the VertexPicker was taking the viewer container from the UI Manager, but the UI Manager never gets initialized if the developer decides to disable the built-in UI by using `components.uiEnabled = false`.
---
> fix(components): 194 - Fixed LengthMeasurement bug while UI Disabled.

- package.json
- src/fragments/FragmentBoundingBox/index.ts
The previous bounding box only allows to use Instanced Meshes. This PR extends it so that it also admits regular meshes.
---
> feat: allow bounding box to use simple meshes

- src/measurement/LengthMeasurement/index.ts
This interacts with the measurement returned by the onAfterCreate to facilitate external management 
i.e. a react list
Note: I think this should be the default `delete` and the current one should be renamed to `deleteHovered`, but that breaks the API.
---
> feat: delete specific measurement

- src/fragments/FragmentHighlighter/index.ts
This PR fixes issue https://github.com/IFCjs/components/issues/149.
---
> fix(components): Fragment highlighter meshes added to ScreenCuller

- src/core/ScreenCuller/index.html
- src/core/ScreenCuller/index.ts
- src/fragments/FragmentBoundingBox/index.ts
- src/fragments/FragmentHighlighter/index.ts
This PR does two things:
1. Implement the [configurable interface](https://docs.thatopen.com/api/interfaces/openbim_components.Configurable) in the ScreenCuller.
2. Fixes a culling problem on highlight meshes.
3. Updated the ScreenCuller example.
---
> feat(components): Implemented setup on ScreenCuller

- src/fragments/FragmentIfcLoader/index.ts
This PR solves issue https://github.com/IFCjs/components/issues/251.
---
> fix: Optional categories reset after initial loading in FragmentIfcLoader

- src/fragments/FragmentTree/index.ts
This PR remove the FragmentTree to be a tool. It mustn't be one because then developers can't create multiple trees.
---
> fix: FragmentTree must not be a tool

- src/civil/RoadNavigator/civil-road/curve-highlighter.ts
- src/civil/RoadNavigator/index.ts
- src/civil/RoadPlanNavigator/index.html
- Highlighting the Curve when selected using the Curve-Highlighter
- Change Highlighter Colour
> Curve Selection onHighlight using Highlighter Class

- src/ifc/IfcPropertiesProcessor/index.ts
I notice a regression in ifcPropertiesProcessor getProperties function :
- model.getProperties is not call with "await" whereas the function is asynchronous
- getPsetProperties and getNestedPsets are call with model (FragmentsGroup) as parameter instead of model.getLocalProperties().
---
- [ x] Bug fix
- [x ] Check that there isn't already a PR that solves the problem the same way to avoid creating a duplicate.
- [x ] Follow the [Conventional Commits v1.0.0](https://www.conventionalcommits.org/en/v1.0.0/) standard for PR naming (e.g. `feat(examples): add hello-world example`).
- [ x] Provide a description in this PR that addresses **what** the PR is solving, or reference the issue that it solves (e.g. `fixes #123`).
> fix-ifcPropertiesProcessor-getProperties

- src/fragments/FragmentHider/index.ts
Simply, an if-clause is needed. In some cases, when We deal with the FragmentTree panel, some retrieved uuids could not point to available fragments.
This happens when FragmentIfcStreamer is being used
> fix: FragmentHider if-guard

- src/fragments/FragmentIfcStreamer/src/geometry-culler-renderer.ts
After streaming an IFC model into the scene, if we call remove(modelID) from the FragmentStreamLoader, an error will be thrown by the loader's GeometryCullerRenderer remove(modelID), because while the _geometry property has been cleared, the _foundGeometry property will still have some of the model's geometry. The error is thrown the next time the culler is updated.
This PR is trying to fix [issue:#345]
There is probably a more thorough approach to fix this issue, but for my use case this worked as intended. I just wanted to at least give attention to this issue.
---
> fix: [BIM Tiles] Error when removing streamed model from scene

- src/civil/RoadElevationNavigator/index.ts
- src/civil/RoadNavigator/index.ts
- src/civil/RoadNavigator/src/kp-manager.ts
- src/civil/RoadPlanNavigator/index.html
- src/civil/RoadPlanNavigator/index.ts
- src/civil/RoadPlanNavigator/src/plan-highlighter.ts
- src/core/Simple2DMarker/src/marker-manager.ts
KP Manager + Supporting Plan-Navigator + Cleanup
> KP Manager + Supporting Plan-Navigator + Cleanup

- packages/components/src/ifc/IfcRelationsIndexer/example.ts
- packages/components/src/ifc/IfcRelationsIndexer/index.ts
- packages/components/src/ifc/IfcRelationsIndexer/src/get-relation-map.ts
This PR adds `IfcRelationsIndexer.processFromWebIfc` to allow an indexMap to be generated `IfcAPI`.
---
> Updated IfcRelationsIndexer to allow indexations from WerbIfc

- package.json
- packages/components-front/src/fragments/FragmentIfcStreamer/src/fragment-stream-loader.ts
- packages/components/src/fragments/FragmentManager/index.ts
- packages/components/src/ifc/IfcRelationsIndexer/index.ts
This PR updates `FragmentManager.load` in order to allow optional properties and indexation files to be passed.
---
> Updates FragmentManager.load

- packages/front/src/measurement/FaceMeasurement/index.ts
The FaceMeasurement component throws during `components.dispose()`.
This occurs when the components are being disposed and the world is disposed
before the `FaceMeasurement`. `components.dispose()` calls `enabled = false` before disposing
individual components which causes issues because `FaceMeasurement` calls `setVisibility(false)` when
`enabled` is set.
N/A
> fix(FaceMeasurement): handle world.isDisposing when setting visibility

- packages/core/src/fragments/IfcLoader/src/ifc-metadata-reader.ts
This is a fix in response to issue #498 
file_description is first checked if it is an array before checking the value of its first element.
---
> fix(core): IFC file containing "$" in header fails to load
